{% set name = "numactl" %}
{% set version = "2.0.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/numactl/numactl.git
  git_rev: v{{ version }}

build:
  # add license_file in about section on refresh.
  number: 1

requirements:
  build:
    - {{ compiler('c') }}             #[ppc_arch != "p10"]
    - {{ compiler('cxx') }}           #[ppc_arch != "p10"]
    - libtool
    - automake
    - autoconf
    - make
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
test:
  commands:
     - which numactl | grep conda

about:
  home: https://github.com/numactl/numactl
  license: GPL-2.0
  license_family: GPL2
  summary: Control NUMA policy for processes or shared memory
  description: Control NUMA policy for processes or shared memory

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
